server:
  port: 8080

spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: jdbc:mysql://localhost:3306/cobang?serverTimezone=Asia/Seoul&useSSL=false
    username: cobangbang
    password: cobangbang
mybatis:
  type-aliases-package: com.example.cobang
  mapper-locations: mybatis/mapper/**/*.xml

logging:
  config: classpath:log4j2.yml