server:
  port: 8080

spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: jdbc:mysql://localhost:3306/cobang
    username: root
    data-password:

logging:
  config: classpath:log4j2.yml